### ISSUE TITLE
Improve Output Writing with Interval-based Map Generation

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/Wflow.jl#354] opened 2024-02-09 13:27 UTC
### Feature type

Adding new functionality

### Improvement Description

The current output writing mechanism lacks the capability to generate maps at specific intervals, which could provide valuable insights into model dynamics and facilitate visual analysis. While not critical, enhancing output writing by incorporating interval-based map generation could significantly improve the utility and interpretability of simulation results.

### Implementation Description

1)Interval-based Map Generation:
Implement functionality to generate maps at specific intervals during simulation execution. These intervals could be defined by the user in the model configuration or based on predefined time steps.
Ensure that the generated maps capture relevant model variables and metrics, such as water levels, flow rates, or spatial distributions of hydrological parameters.

2)Output File Management:
Develop a structured approach to manage output files generated during simulation runs, including naming conventions, file formats, and storage locations.
Consider integrating the interval-based map generation functionality with existing output file management systems to ensure consistency and ease of use.

**Comment by verseve** [comment] 2024-02-29 14:33
I think this is a duplicate of two issues: https://github.com/Deltares/Wflow.jl/issues/125 and https://github.com/Deltares/Wflow.jl/issues/189.

**Closed by verseve** 2024-02-29 14:33 UTC
Labels: duplicate, user-experience, needs refinement
